bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1012_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1012_1.query.gz SR/per_sample_SVs/RGP_1012_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1012_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1012_2.query.gz SR/per_sample_SVs/RGP_1012_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1012_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1012_3.query.gz SR/per_sample_SVs/RGP_1012_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_101_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_101_1.query.gz SR/per_sample_SVs/RGP_101_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_101_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_101_2.query.gz SR/per_sample_SVs/RGP_101_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_101_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_101_3.query.gz SR/per_sample_SVs/RGP_101_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1056_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1056_1.query.gz SR/per_sample_SVs/RGP_1056_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1056_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1056_2.query.gz SR/per_sample_SVs/RGP_1056_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1056_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1056_3.query.gz SR/per_sample_SVs/RGP_1056_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1059_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1059_1.query.gz SR/per_sample_SVs/RGP_1059_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1059_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1059_2.query.gz SR/per_sample_SVs/RGP_1059_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1059_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1059_3.query.gz SR/per_sample_SVs/RGP_1059_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1061_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1061_3.query.gz SR/per_sample_SVs/RGP_1061_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1109_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1109_3.query.gz SR/per_sample_SVs/RGP_1109_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1170_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1170_3.query.gz SR/per_sample_SVs/RGP_1170_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1253_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1253_3.query.gz SR/per_sample_SVs/RGP_1253_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1364_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1364_3.query.gz SR/per_sample_SVs/RGP_1364_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1396_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1396_1.query.gz SR/per_sample_SVs/RGP_1396_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1396_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1396_2.query.gz SR/per_sample_SVs/RGP_1396_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1396_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1396_3.query.gz SR/per_sample_SVs/RGP_1396_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1446_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1446_1.query.gz SR/per_sample_SVs/RGP_1446_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1446_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1446_2.query.gz SR/per_sample_SVs/RGP_1446_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1446_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1446_3.query.gz SR/per_sample_SVs/RGP_1446_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1456_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1456_1.query.gz SR/per_sample_SVs/RGP_1456_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1456_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1456_2.query.gz SR/per_sample_SVs/RGP_1456_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1456_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1456_3.query.gz SR/per_sample_SVs/RGP_1456_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1547_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1547_3.query.gz SR/per_sample_SVs/RGP_1547_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1547_4.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1547_4.query.gz SR/per_sample_SVs/RGP_1547_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1547_6.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1547_6.query.gz SR/per_sample_SVs/RGP_1547_6.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1554_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1554_1.query.gz SR/per_sample_SVs/RGP_1554_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1554_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1554_2.query.gz SR/per_sample_SVs/RGP_1554_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1554_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1554_3.query.gz SR/per_sample_SVs/RGP_1554_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1556_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1556_3.query.gz SR/per_sample_SVs/RGP_1556_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1581_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1581_3.query.gz SR/per_sample_SVs/RGP_1581_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1598_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1598_3.query.gz SR/per_sample_SVs/RGP_1598_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1604_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1604_1.query.gz SR/per_sample_SVs/RGP_1604_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1604_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1604_2.query.gz SR/per_sample_SVs/RGP_1604_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1604_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1604_3.query.gz SR/per_sample_SVs/RGP_1604_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1606_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1606_1.query.gz SR/per_sample_SVs/RGP_1606_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1606_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1606_2.query.gz SR/per_sample_SVs/RGP_1606_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1606_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1606_3.query.gz SR/per_sample_SVs/RGP_1606_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1641_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1641_1.query.gz SR/per_sample_SVs/RGP_1641_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1641_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1641_2.query.gz SR/per_sample_SVs/RGP_1641_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1641_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1641_3.query.gz SR/per_sample_SVs/RGP_1641_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1670_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1670_1.query.gz SR/per_sample_SVs/RGP_1670_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1670_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1670_2.query.gz SR/per_sample_SVs/RGP_1670_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1670_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1670_3.query.gz SR/per_sample_SVs/RGP_1670_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1706_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1706_2.query.gz SR/per_sample_SVs/RGP_1706_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1706_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1706_3.query.gz SR/per_sample_SVs/RGP_1706_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1724_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1724_1.query.gz SR/per_sample_SVs/RGP_1724_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1724_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1724_2.query.gz SR/per_sample_SVs/RGP_1724_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1724_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1724_3.query.gz SR/per_sample_SVs/RGP_1724_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1750_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1750_1.query.gz SR/per_sample_SVs/RGP_1750_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1750_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1750_2.query.gz SR/per_sample_SVs/RGP_1750_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1750_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1750_3.query.gz SR/per_sample_SVs/RGP_1750_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1772_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1772_1.query.gz SR/per_sample_SVs/RGP_1772_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1772_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1772_2.query.gz SR/per_sample_SVs/RGP_1772_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1772_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1772_3.query.gz SR/per_sample_SVs/RGP_1772_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1777_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1777_1.query.gz SR/per_sample_SVs/RGP_1777_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1777_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1777_2.query.gz SR/per_sample_SVs/RGP_1777_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1777_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1777_3.query.gz SR/per_sample_SVs/RGP_1777_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1780_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1780_1.query.gz SR/per_sample_SVs/RGP_1780_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1780_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1780_2.query.gz SR/per_sample_SVs/RGP_1780_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1780_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1780_3.query.gz SR/per_sample_SVs/RGP_1780_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1786_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1786_3.query.gz SR/per_sample_SVs/RGP_1786_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1793_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1793_1.query.gz SR/per_sample_SVs/RGP_1793_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1793_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1793_2.query.gz SR/per_sample_SVs/RGP_1793_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1793_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1793_3.query.gz SR/per_sample_SVs/RGP_1793_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1830_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1830_2.query.gz SR/per_sample_SVs/RGP_1830_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1830_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1830_3.query.gz SR/per_sample_SVs/RGP_1830_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1831_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1831_1.query.gz SR/per_sample_SVs/RGP_1831_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1836_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1836_1.query.gz SR/per_sample_SVs/RGP_1836_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1836_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1836_2.query.gz SR/per_sample_SVs/RGP_1836_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1836_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1836_3.query.gz SR/per_sample_SVs/RGP_1836_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1862_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1862_3.query.gz SR/per_sample_SVs/RGP_1862_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1883_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1883_1.query.gz SR/per_sample_SVs/RGP_1883_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1883_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1883_2.query.gz SR/per_sample_SVs/RGP_1883_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1883_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1883_3.query.gz SR/per_sample_SVs/RGP_1883_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_1890_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1890_3.query.gz SR/per_sample_SVs/RGP_1890_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2003_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2003_1.query.gz SR/per_sample_SVs/RGP_2003_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2003_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2003_2.query.gz SR/per_sample_SVs/RGP_2003_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2003_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2003_3.query.gz SR/per_sample_SVs/RGP_2003_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2007_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2007_1.query.gz SR/per_sample_SVs/RGP_2007_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2007_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2007_2.query.gz SR/per_sample_SVs/RGP_2007_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2007_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2007_3.query.gz SR/per_sample_SVs/RGP_2007_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2021_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2021_1.query.gz SR/per_sample_SVs/RGP_2021_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2021_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2021_2.query.gz SR/per_sample_SVs/RGP_2021_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2021_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2021_3.query.gz SR/per_sample_SVs/RGP_2021_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2025_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2025_2.query.gz SR/per_sample_SVs/RGP_2025_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2025_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2025_3.query.gz SR/per_sample_SVs/RGP_2025_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2080_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2080_3.query.gz SR/per_sample_SVs/RGP_2080_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2083_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2083_1.query.gz SR/per_sample_SVs/RGP_2083_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2083_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2083_2.query.gz SR/per_sample_SVs/RGP_2083_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2083_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2083_3.query.gz SR/per_sample_SVs/RGP_2083_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2120_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2120_1.query.gz SR/per_sample_SVs/RGP_2120_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2120_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2120_2.query.gz SR/per_sample_SVs/RGP_2120_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2120_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2120_3.query.gz SR/per_sample_SVs/RGP_2120_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2122_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2122_1.query.gz SR/per_sample_SVs/RGP_2122_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2122_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2122_2.query.gz SR/per_sample_SVs/RGP_2122_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2122_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2122_3.query.gz SR/per_sample_SVs/RGP_2122_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2131_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2131_1.query.gz SR/per_sample_SVs/RGP_2131_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2131_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2131_2.query.gz SR/per_sample_SVs/RGP_2131_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2131_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2131_3.query.gz SR/per_sample_SVs/RGP_2131_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2131_4.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2131_4.query.gz SR/per_sample_SVs/RGP_2131_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2150_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2150_1.query.gz SR/per_sample_SVs/RGP_2150_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2150_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2150_2.query.gz SR/per_sample_SVs/RGP_2150_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2150_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2150_3.query.gz SR/per_sample_SVs/RGP_2150_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2158_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2158_1.query.gz SR/per_sample_SVs/RGP_2158_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2158_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2158_2.query.gz SR/per_sample_SVs/RGP_2158_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2158_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2158_3.query.gz SR/per_sample_SVs/RGP_2158_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2159_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2159_1.query.gz SR/per_sample_SVs/RGP_2159_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2159_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2159_2.query.gz SR/per_sample_SVs/RGP_2159_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2159_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2159_3.query.gz SR/per_sample_SVs/RGP_2159_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2166_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2166_1.query.gz SR/per_sample_SVs/RGP_2166_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2166_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2166_3.query.gz SR/per_sample_SVs/RGP_2166_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2167_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2167_2.query.gz SR/per_sample_SVs/RGP_2167_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2167_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2167_3.query.gz SR/per_sample_SVs/RGP_2167_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2174_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2174_1.query.gz SR/per_sample_SVs/RGP_2174_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2174_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2174_2.query.gz SR/per_sample_SVs/RGP_2174_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2174_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2174_3.query.gz SR/per_sample_SVs/RGP_2174_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2176_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2176_1.query.gz SR/per_sample_SVs/RGP_2176_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2176_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2176_2.query.gz SR/per_sample_SVs/RGP_2176_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2176_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2176_3.query.gz SR/per_sample_SVs/RGP_2176_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2177_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2177_3.query.gz SR/per_sample_SVs/RGP_2177_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2188_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2188_1.query.gz SR/per_sample_SVs/RGP_2188_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2188_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2188_2.query.gz SR/per_sample_SVs/RGP_2188_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2188_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2188_3.query.gz SR/per_sample_SVs/RGP_2188_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2210_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2210_1.query.gz SR/per_sample_SVs/RGP_2210_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2210_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2210_2.query.gz SR/per_sample_SVs/RGP_2210_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2210_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2210_3.query.gz SR/per_sample_SVs/RGP_2210_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2211_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2211_1.query.gz SR/per_sample_SVs/RGP_2211_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2211_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2211_2.query.gz SR/per_sample_SVs/RGP_2211_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2211_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2211_3.query.gz SR/per_sample_SVs/RGP_2211_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2218_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2218_1.query.gz SR/per_sample_SVs/RGP_2218_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2218_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2218_2.query.gz SR/per_sample_SVs/RGP_2218_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2218_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2218_3.query.gz SR/per_sample_SVs/RGP_2218_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2222_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2222_1.query.gz SR/per_sample_SVs/RGP_2222_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2222_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2222_2.query.gz SR/per_sample_SVs/RGP_2222_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2222_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2222_3.query.gz SR/per_sample_SVs/RGP_2222_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2222_4.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2222_4.query.gz SR/per_sample_SVs/RGP_2222_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2222_5.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2222_5.query.gz SR/per_sample_SVs/RGP_2222_5.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2248_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2248_1.query.gz SR/per_sample_SVs/RGP_2248_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2248_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2248_2.query.gz SR/per_sample_SVs/RGP_2248_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2248_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2248_3.query.gz SR/per_sample_SVs/RGP_2248_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2282_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2282_3.query.gz SR/per_sample_SVs/RGP_2282_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2283_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2283_3.query.gz SR/per_sample_SVs/RGP_2283_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_230_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_230_1.query.gz SR/per_sample_SVs/RGP_230_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_230_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_230_2.query.gz SR/per_sample_SVs/RGP_230_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_230_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_230_3.query.gz SR/per_sample_SVs/RGP_230_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2353_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2353_3.query.gz SR/per_sample_SVs/RGP_2353_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2360_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2360_1.query.gz SR/per_sample_SVs/RGP_2360_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2360_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2360_2.query.gz SR/per_sample_SVs/RGP_2360_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2360_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2360_3.query.gz SR/per_sample_SVs/RGP_2360_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2488_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2488_1.query.gz SR/per_sample_SVs/RGP_2488_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2488_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2488_2.query.gz SR/per_sample_SVs/RGP_2488_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2488_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2488_3.query.gz SR/per_sample_SVs/RGP_2488_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2640_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2640_1.query.gz SR/per_sample_SVs/RGP_2640_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2640_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2640_2.query.gz SR/per_sample_SVs/RGP_2640_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_2640_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2640_3.query.gz SR/per_sample_SVs/RGP_2640_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_469_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_469_1.query.gz SR/per_sample_SVs/RGP_469_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_469_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_469_2.query.gz SR/per_sample_SVs/RGP_469_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_469_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_469_3.query.gz SR/per_sample_SVs/RGP_469_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_612_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_612_3.query.gz SR/per_sample_SVs/RGP_612_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_612_4.bed -p LR_vs_SR LR/per_sample_SVs/RGP_612_4.query.gz SR/per_sample_SVs/RGP_612_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_654_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_654_3.query.gz SR/per_sample_SVs/RGP_654_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_655_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_655_1.query.gz SR/per_sample_SVs/RGP_655_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_655_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_655_2.query.gz SR/per_sample_SVs/RGP_655_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_655_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_655_3.query.gz SR/per_sample_SVs/RGP_655_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_657_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_657_1.query.gz SR/per_sample_SVs/RGP_657_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_657_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_657_2.query.gz SR/per_sample_SVs/RGP_657_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_657_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_657_3.query.gz SR/per_sample_SVs/RGP_657_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_688_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_688_1.query.gz SR/per_sample_SVs/RGP_688_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_688_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_688_2.query.gz SR/per_sample_SVs/RGP_688_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_688_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_688_3.query.gz SR/per_sample_SVs/RGP_688_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_732_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_732_1.query.gz SR/per_sample_SVs/RGP_732_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_732_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_732_2.query.gz SR/per_sample_SVs/RGP_732_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_732_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_732_3.query.gz SR/per_sample_SVs/RGP_732_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_869_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_869_3.query.gz SR/per_sample_SVs/RGP_869_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_924_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_924_3.query.gz SR/per_sample_SVs/RGP_924_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_931_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_931_3.query.gz SR/per_sample_SVs/RGP_931_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.PB.RGP_955_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_955_3.query.gz SR/per_sample_SVs/RGP_955_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1012_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1012_1.query.gz LR/per_sample_SVs/RGP_1012_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1012_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1012_2.query.gz LR/per_sample_SVs/RGP_1012_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1012_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1012_3.query.gz LR/per_sample_SVs/RGP_1012_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_101_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_101_1.query.gz LR/per_sample_SVs/RGP_101_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_101_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_101_2.query.gz LR/per_sample_SVs/RGP_101_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_101_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_101_3.query.gz LR/per_sample_SVs/RGP_101_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1056_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1056_1.query.gz LR/per_sample_SVs/RGP_1056_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1056_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1056_2.query.gz LR/per_sample_SVs/RGP_1056_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1056_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1056_3.query.gz LR/per_sample_SVs/RGP_1056_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1059_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1059_1.query.gz LR/per_sample_SVs/RGP_1059_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1059_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1059_2.query.gz LR/per_sample_SVs/RGP_1059_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1059_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1059_3.query.gz LR/per_sample_SVs/RGP_1059_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1061_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1061_3.query.gz LR/per_sample_SVs/RGP_1061_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1109_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1109_3.query.gz LR/per_sample_SVs/RGP_1109_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1170_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1170_3.query.gz LR/per_sample_SVs/RGP_1170_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1253_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1253_3.query.gz LR/per_sample_SVs/RGP_1253_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1364_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1364_3.query.gz LR/per_sample_SVs/RGP_1364_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1396_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1396_1.query.gz LR/per_sample_SVs/RGP_1396_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1396_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1396_2.query.gz LR/per_sample_SVs/RGP_1396_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1396_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1396_3.query.gz LR/per_sample_SVs/RGP_1396_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1446_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1446_1.query.gz LR/per_sample_SVs/RGP_1446_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1446_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1446_2.query.gz LR/per_sample_SVs/RGP_1446_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1446_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1446_3.query.gz LR/per_sample_SVs/RGP_1446_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1456_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1456_1.query.gz LR/per_sample_SVs/RGP_1456_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1456_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1456_2.query.gz LR/per_sample_SVs/RGP_1456_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1456_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1456_3.query.gz LR/per_sample_SVs/RGP_1456_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1547_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1547_3.query.gz LR/per_sample_SVs/RGP_1547_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1547_4.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1547_4.query.gz LR/per_sample_SVs/RGP_1547_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1547_6.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1547_6.query.gz LR/per_sample_SVs/RGP_1547_6.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1554_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1554_1.query.gz LR/per_sample_SVs/RGP_1554_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1554_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1554_2.query.gz LR/per_sample_SVs/RGP_1554_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1554_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1554_3.query.gz LR/per_sample_SVs/RGP_1554_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1556_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1556_3.query.gz LR/per_sample_SVs/RGP_1556_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1581_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1581_3.query.gz LR/per_sample_SVs/RGP_1581_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1598_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1598_3.query.gz LR/per_sample_SVs/RGP_1598_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1604_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1604_1.query.gz LR/per_sample_SVs/RGP_1604_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1604_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1604_2.query.gz LR/per_sample_SVs/RGP_1604_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1604_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1604_3.query.gz LR/per_sample_SVs/RGP_1604_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1606_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1606_1.query.gz LR/per_sample_SVs/RGP_1606_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1606_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1606_2.query.gz LR/per_sample_SVs/RGP_1606_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1606_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1606_3.query.gz LR/per_sample_SVs/RGP_1606_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1641_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1641_1.query.gz LR/per_sample_SVs/RGP_1641_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1641_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1641_2.query.gz LR/per_sample_SVs/RGP_1641_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1641_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1641_3.query.gz LR/per_sample_SVs/RGP_1641_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1670_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1670_1.query.gz LR/per_sample_SVs/RGP_1670_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1670_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1670_2.query.gz LR/per_sample_SVs/RGP_1670_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1670_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1670_3.query.gz LR/per_sample_SVs/RGP_1670_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1706_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1706_2.query.gz LR/per_sample_SVs/RGP_1706_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1706_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1706_3.query.gz LR/per_sample_SVs/RGP_1706_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1724_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1724_1.query.gz LR/per_sample_SVs/RGP_1724_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1724_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1724_2.query.gz LR/per_sample_SVs/RGP_1724_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1724_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1724_3.query.gz LR/per_sample_SVs/RGP_1724_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1750_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1750_1.query.gz LR/per_sample_SVs/RGP_1750_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1750_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1750_2.query.gz LR/per_sample_SVs/RGP_1750_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1750_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1750_3.query.gz LR/per_sample_SVs/RGP_1750_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1772_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1772_1.query.gz LR/per_sample_SVs/RGP_1772_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1772_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1772_2.query.gz LR/per_sample_SVs/RGP_1772_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1772_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1772_3.query.gz LR/per_sample_SVs/RGP_1772_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1777_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1777_1.query.gz LR/per_sample_SVs/RGP_1777_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1777_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1777_2.query.gz LR/per_sample_SVs/RGP_1777_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1777_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1777_3.query.gz LR/per_sample_SVs/RGP_1777_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1780_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1780_1.query.gz LR/per_sample_SVs/RGP_1780_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1780_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1780_2.query.gz LR/per_sample_SVs/RGP_1780_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1780_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1780_3.query.gz LR/per_sample_SVs/RGP_1780_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1786_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1786_3.query.gz LR/per_sample_SVs/RGP_1786_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1793_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1793_1.query.gz LR/per_sample_SVs/RGP_1793_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1793_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1793_2.query.gz LR/per_sample_SVs/RGP_1793_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1793_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1793_3.query.gz LR/per_sample_SVs/RGP_1793_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1830_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1830_2.query.gz LR/per_sample_SVs/RGP_1830_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1830_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1830_3.query.gz LR/per_sample_SVs/RGP_1830_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1831_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1831_1.query.gz LR/per_sample_SVs/RGP_1831_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1836_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1836_1.query.gz LR/per_sample_SVs/RGP_1836_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1836_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1836_2.query.gz LR/per_sample_SVs/RGP_1836_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1836_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1836_3.query.gz LR/per_sample_SVs/RGP_1836_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1862_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1862_3.query.gz LR/per_sample_SVs/RGP_1862_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1883_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1883_1.query.gz LR/per_sample_SVs/RGP_1883_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1883_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1883_2.query.gz LR/per_sample_SVs/RGP_1883_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1883_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1883_3.query.gz LR/per_sample_SVs/RGP_1883_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_1890_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1890_3.query.gz LR/per_sample_SVs/RGP_1890_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2003_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2003_1.query.gz LR/per_sample_SVs/RGP_2003_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2003_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2003_2.query.gz LR/per_sample_SVs/RGP_2003_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2003_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2003_3.query.gz LR/per_sample_SVs/RGP_2003_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2007_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2007_1.query.gz LR/per_sample_SVs/RGP_2007_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2007_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2007_2.query.gz LR/per_sample_SVs/RGP_2007_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2007_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2007_3.query.gz LR/per_sample_SVs/RGP_2007_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2021_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2021_1.query.gz LR/per_sample_SVs/RGP_2021_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2021_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2021_2.query.gz LR/per_sample_SVs/RGP_2021_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2021_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2021_3.query.gz LR/per_sample_SVs/RGP_2021_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2025_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2025_2.query.gz LR/per_sample_SVs/RGP_2025_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2025_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2025_3.query.gz LR/per_sample_SVs/RGP_2025_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2080_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2080_3.query.gz LR/per_sample_SVs/RGP_2080_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2083_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2083_1.query.gz LR/per_sample_SVs/RGP_2083_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2083_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2083_2.query.gz LR/per_sample_SVs/RGP_2083_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2083_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2083_3.query.gz LR/per_sample_SVs/RGP_2083_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2120_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2120_1.query.gz LR/per_sample_SVs/RGP_2120_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2120_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2120_2.query.gz LR/per_sample_SVs/RGP_2120_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2120_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2120_3.query.gz LR/per_sample_SVs/RGP_2120_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2122_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2122_1.query.gz LR/per_sample_SVs/RGP_2122_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2122_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2122_2.query.gz LR/per_sample_SVs/RGP_2122_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2122_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2122_3.query.gz LR/per_sample_SVs/RGP_2122_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2131_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2131_1.query.gz LR/per_sample_SVs/RGP_2131_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2131_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2131_2.query.gz LR/per_sample_SVs/RGP_2131_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2131_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2131_3.query.gz LR/per_sample_SVs/RGP_2131_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2131_4.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2131_4.query.gz LR/per_sample_SVs/RGP_2131_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2150_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2150_1.query.gz LR/per_sample_SVs/RGP_2150_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2150_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2150_2.query.gz LR/per_sample_SVs/RGP_2150_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2150_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2150_3.query.gz LR/per_sample_SVs/RGP_2150_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2158_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2158_1.query.gz LR/per_sample_SVs/RGP_2158_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2158_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2158_2.query.gz LR/per_sample_SVs/RGP_2158_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2158_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2158_3.query.gz LR/per_sample_SVs/RGP_2158_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2159_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2159_1.query.gz LR/per_sample_SVs/RGP_2159_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2159_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2159_2.query.gz LR/per_sample_SVs/RGP_2159_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2159_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2159_3.query.gz LR/per_sample_SVs/RGP_2159_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2166_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2166_1.query.gz LR/per_sample_SVs/RGP_2166_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2166_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2166_3.query.gz LR/per_sample_SVs/RGP_2166_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2167_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2167_2.query.gz LR/per_sample_SVs/RGP_2167_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2167_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2167_3.query.gz LR/per_sample_SVs/RGP_2167_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2174_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2174_1.query.gz LR/per_sample_SVs/RGP_2174_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2174_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2174_2.query.gz LR/per_sample_SVs/RGP_2174_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2174_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2174_3.query.gz LR/per_sample_SVs/RGP_2174_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2176_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2176_1.query.gz LR/per_sample_SVs/RGP_2176_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2176_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2176_2.query.gz LR/per_sample_SVs/RGP_2176_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2176_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2176_3.query.gz LR/per_sample_SVs/RGP_2176_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2177_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2177_3.query.gz LR/per_sample_SVs/RGP_2177_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2188_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2188_1.query.gz LR/per_sample_SVs/RGP_2188_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2188_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2188_2.query.gz LR/per_sample_SVs/RGP_2188_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2188_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2188_3.query.gz LR/per_sample_SVs/RGP_2188_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2210_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2210_1.query.gz LR/per_sample_SVs/RGP_2210_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2210_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2210_2.query.gz LR/per_sample_SVs/RGP_2210_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2210_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2210_3.query.gz LR/per_sample_SVs/RGP_2210_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2211_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2211_1.query.gz LR/per_sample_SVs/RGP_2211_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2211_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2211_2.query.gz LR/per_sample_SVs/RGP_2211_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2211_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2211_3.query.gz LR/per_sample_SVs/RGP_2211_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2218_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2218_1.query.gz LR/per_sample_SVs/RGP_2218_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2218_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2218_2.query.gz LR/per_sample_SVs/RGP_2218_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2218_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2218_3.query.gz LR/per_sample_SVs/RGP_2218_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2222_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2222_1.query.gz LR/per_sample_SVs/RGP_2222_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2222_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2222_2.query.gz LR/per_sample_SVs/RGP_2222_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2222_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2222_3.query.gz LR/per_sample_SVs/RGP_2222_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2222_4.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2222_4.query.gz LR/per_sample_SVs/RGP_2222_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2222_5.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2222_5.query.gz LR/per_sample_SVs/RGP_2222_5.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2248_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2248_1.query.gz LR/per_sample_SVs/RGP_2248_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2248_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2248_2.query.gz LR/per_sample_SVs/RGP_2248_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2248_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2248_3.query.gz LR/per_sample_SVs/RGP_2248_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2282_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2282_3.query.gz LR/per_sample_SVs/RGP_2282_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2283_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2283_3.query.gz LR/per_sample_SVs/RGP_2283_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_230_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_230_1.query.gz LR/per_sample_SVs/RGP_230_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_230_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_230_2.query.gz LR/per_sample_SVs/RGP_230_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_230_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_230_3.query.gz LR/per_sample_SVs/RGP_230_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2353_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2353_3.query.gz LR/per_sample_SVs/RGP_2353_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2360_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2360_1.query.gz LR/per_sample_SVs/RGP_2360_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2360_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2360_2.query.gz LR/per_sample_SVs/RGP_2360_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2360_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2360_3.query.gz LR/per_sample_SVs/RGP_2360_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2488_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2488_1.query.gz LR/per_sample_SVs/RGP_2488_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2488_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2488_2.query.gz LR/per_sample_SVs/RGP_2488_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2488_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2488_3.query.gz LR/per_sample_SVs/RGP_2488_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2640_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2640_1.query.gz LR/per_sample_SVs/RGP_2640_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2640_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2640_2.query.gz LR/per_sample_SVs/RGP_2640_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_2640_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2640_3.query.gz LR/per_sample_SVs/RGP_2640_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_469_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_469_1.query.gz LR/per_sample_SVs/RGP_469_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_469_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_469_2.query.gz LR/per_sample_SVs/RGP_469_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_469_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_469_3.query.gz LR/per_sample_SVs/RGP_469_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_612_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_612_3.query.gz LR/per_sample_SVs/RGP_612_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_612_4.bed -p SR_vs_LR SR/per_sample_SVs/RGP_612_4.query.gz LR/per_sample_SVs/RGP_612_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_654_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_654_3.query.gz LR/per_sample_SVs/RGP_654_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_655_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_655_1.query.gz LR/per_sample_SVs/RGP_655_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_655_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_655_2.query.gz LR/per_sample_SVs/RGP_655_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_655_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_655_3.query.gz LR/per_sample_SVs/RGP_655_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_657_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_657_1.query.gz LR/per_sample_SVs/RGP_657_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_657_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_657_2.query.gz LR/per_sample_SVs/RGP_657_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_657_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_657_3.query.gz LR/per_sample_SVs/RGP_657_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_688_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_688_1.query.gz LR/per_sample_SVs/RGP_688_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_688_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_688_2.query.gz LR/per_sample_SVs/RGP_688_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_688_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_688_3.query.gz LR/per_sample_SVs/RGP_688_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_732_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_732_1.query.gz LR/per_sample_SVs/RGP_732_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_732_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_732_2.query.gz LR/per_sample_SVs/RGP_732_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_732_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_732_3.query.gz LR/per_sample_SVs/RGP_732_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_869_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_869_3.query.gz LR/per_sample_SVs/RGP_869_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_924_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_924_3.query.gz LR/per_sample_SVs/RGP_924_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_931_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_931_3.query.gz LR/per_sample_SVs/RGP_931_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.PB.RGP_955_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_955_3.query.gz LR/per_sample_SVs/RGP_955_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1081_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1081_1.query.gz SR/per_sample_SVs/RGP_1081_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1081_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1081_2.query.gz SR/per_sample_SVs/RGP_1081_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1081_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1081_3.query.gz SR/per_sample_SVs/RGP_1081_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1219_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1219_1.query.gz SR/per_sample_SVs/RGP_1219_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1219_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1219_2.query.gz SR/per_sample_SVs/RGP_1219_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1219_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1219_3.query.gz SR/per_sample_SVs/RGP_1219_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1219_4.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1219_4.query.gz SR/per_sample_SVs/RGP_1219_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1238_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1238_1.query.gz SR/per_sample_SVs/RGP_1238_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1238_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1238_2.query.gz SR/per_sample_SVs/RGP_1238_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1238_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1238_3.query.gz SR/per_sample_SVs/RGP_1238_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_123_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_123_1.query.gz SR/per_sample_SVs/RGP_123_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_123_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_123_2.query.gz SR/per_sample_SVs/RGP_123_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_123_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_123_3.query.gz SR/per_sample_SVs/RGP_123_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_12_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_12_1.query.gz SR/per_sample_SVs/RGP_12_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_12_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_12_2.query.gz SR/per_sample_SVs/RGP_12_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_12_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_12_3.query.gz SR/per_sample_SVs/RGP_12_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1316_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1316_1.query.gz SR/per_sample_SVs/RGP_1316_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1316_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1316_2.query.gz SR/per_sample_SVs/RGP_1316_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1316_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1316_3.query.gz SR/per_sample_SVs/RGP_1316_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1360_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1360_1.query.gz SR/per_sample_SVs/RGP_1360_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1360_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1360_2.query.gz SR/per_sample_SVs/RGP_1360_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1360_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1360_3.query.gz SR/per_sample_SVs/RGP_1360_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1395_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1395_1.query.gz SR/per_sample_SVs/RGP_1395_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1395_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1395_2.query.gz SR/per_sample_SVs/RGP_1395_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1395_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1395_3.query.gz SR/per_sample_SVs/RGP_1395_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1608_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1608_1.query.gz SR/per_sample_SVs/RGP_1608_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1608_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1608_2.query.gz SR/per_sample_SVs/RGP_1608_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1608_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1608_3.query.gz SR/per_sample_SVs/RGP_1608_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1630_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1630_1.query.gz SR/per_sample_SVs/RGP_1630_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1630_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1630_2.query.gz SR/per_sample_SVs/RGP_1630_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1630_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1630_3.query.gz SR/per_sample_SVs/RGP_1630_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1770_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1770_1.query.gz SR/per_sample_SVs/RGP_1770_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1770_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1770_2.query.gz SR/per_sample_SVs/RGP_1770_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_1770_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_1770_3.query.gz SR/per_sample_SVs/RGP_1770_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_2040_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2040_1.query.gz SR/per_sample_SVs/RGP_2040_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_2040_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2040_2.query.gz SR/per_sample_SVs/RGP_2040_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_2040_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_2040_3.query.gz SR/per_sample_SVs/RGP_2040_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_25_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_25_1.query.gz SR/per_sample_SVs/RGP_25_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_25_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_25_2.query.gz SR/per_sample_SVs/RGP_25_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_25_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_25_3.query.gz SR/per_sample_SVs/RGP_25_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_558_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_558_1.query.gz SR/per_sample_SVs/RGP_558_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_558_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_558_2.query.gz SR/per_sample_SVs/RGP_558_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_558_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_558_3.query.gz SR/per_sample_SVs/RGP_558_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_607_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_607_1.query.gz SR/per_sample_SVs/RGP_607_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_607_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_607_2.query.gz SR/per_sample_SVs/RGP_607_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_607_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_607_3.query.gz SR/per_sample_SVs/RGP_607_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_686_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_686_1.query.gz SR/per_sample_SVs/RGP_686_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_686_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_686_2.query.gz SR/per_sample_SVs/RGP_686_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_686_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_686_3.query.gz SR/per_sample_SVs/RGP_686_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_696_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_696_1.query.gz SR/per_sample_SVs/RGP_696_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_696_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_696_2.query.gz SR/per_sample_SVs/RGP_696_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_696_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_696_3.query.gz SR/per_sample_SVs/RGP_696_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_731_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_731_1.query.gz SR/per_sample_SVs/RGP_731_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_731_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_731_2.query.gz SR/per_sample_SVs/RGP_731_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_731_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_731_3.query.gz SR/per_sample_SVs/RGP_731_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_858_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_858_1.query.gz SR/per_sample_SVs/RGP_858_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_858_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_858_2.query.gz SR/per_sample_SVs/RGP_858_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_858_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_858_3.query.gz SR/per_sample_SVs/RGP_858_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_876_1.bed -p LR_vs_SR LR/per_sample_SVs/RGP_876_1.query.gz SR/per_sample_SVs/RGP_876_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_876_2.bed -p LR_vs_SR LR/per_sample_SVs/RGP_876_2.query.gz SR/per_sample_SVs/RGP_876_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/LR_vs_SR.ONT.RGP_876_3.bed -p LR_vs_SR LR/per_sample_SVs/RGP_876_3.query.gz SR/per_sample_SVs/RGP_876_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1081_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1081_1.query.gz LR/per_sample_SVs/RGP_1081_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1081_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1081_2.query.gz LR/per_sample_SVs/RGP_1081_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1081_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1081_3.query.gz LR/per_sample_SVs/RGP_1081_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1219_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1219_1.query.gz LR/per_sample_SVs/RGP_1219_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1219_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1219_2.query.gz LR/per_sample_SVs/RGP_1219_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1219_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1219_3.query.gz LR/per_sample_SVs/RGP_1219_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1219_4.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1219_4.query.gz LR/per_sample_SVs/RGP_1219_4.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1238_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1238_1.query.gz LR/per_sample_SVs/RGP_1238_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1238_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1238_2.query.gz LR/per_sample_SVs/RGP_1238_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1238_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1238_3.query.gz LR/per_sample_SVs/RGP_1238_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_123_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_123_1.query.gz LR/per_sample_SVs/RGP_123_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_123_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_123_2.query.gz LR/per_sample_SVs/RGP_123_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_123_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_123_3.query.gz LR/per_sample_SVs/RGP_123_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_12_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_12_1.query.gz LR/per_sample_SVs/RGP_12_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_12_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_12_2.query.gz LR/per_sample_SVs/RGP_12_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_12_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_12_3.query.gz LR/per_sample_SVs/RGP_12_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1316_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1316_1.query.gz LR/per_sample_SVs/RGP_1316_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1316_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1316_2.query.gz LR/per_sample_SVs/RGP_1316_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1316_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1316_3.query.gz LR/per_sample_SVs/RGP_1316_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1360_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1360_1.query.gz LR/per_sample_SVs/RGP_1360_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1360_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1360_2.query.gz LR/per_sample_SVs/RGP_1360_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1360_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1360_3.query.gz LR/per_sample_SVs/RGP_1360_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1395_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1395_1.query.gz LR/per_sample_SVs/RGP_1395_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1395_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1395_2.query.gz LR/per_sample_SVs/RGP_1395_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1395_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1395_3.query.gz LR/per_sample_SVs/RGP_1395_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1608_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1608_1.query.gz LR/per_sample_SVs/RGP_1608_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1608_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1608_2.query.gz LR/per_sample_SVs/RGP_1608_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1608_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1608_3.query.gz LR/per_sample_SVs/RGP_1608_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1630_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1630_1.query.gz LR/per_sample_SVs/RGP_1630_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1630_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1630_2.query.gz LR/per_sample_SVs/RGP_1630_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1630_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1630_3.query.gz LR/per_sample_SVs/RGP_1630_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1770_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1770_1.query.gz LR/per_sample_SVs/RGP_1770_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1770_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1770_2.query.gz LR/per_sample_SVs/RGP_1770_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_1770_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_1770_3.query.gz LR/per_sample_SVs/RGP_1770_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_2040_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2040_1.query.gz LR/per_sample_SVs/RGP_2040_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_2040_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2040_2.query.gz LR/per_sample_SVs/RGP_2040_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_2040_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_2040_3.query.gz LR/per_sample_SVs/RGP_2040_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_25_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_25_1.query.gz LR/per_sample_SVs/RGP_25_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_25_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_25_2.query.gz LR/per_sample_SVs/RGP_25_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_25_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_25_3.query.gz LR/per_sample_SVs/RGP_25_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_558_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_558_1.query.gz LR/per_sample_SVs/RGP_558_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_558_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_558_2.query.gz LR/per_sample_SVs/RGP_558_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_558_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_558_3.query.gz LR/per_sample_SVs/RGP_558_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_607_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_607_1.query.gz LR/per_sample_SVs/RGP_607_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_607_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_607_2.query.gz LR/per_sample_SVs/RGP_607_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_607_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_607_3.query.gz LR/per_sample_SVs/RGP_607_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_686_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_686_1.query.gz LR/per_sample_SVs/RGP_686_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_686_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_686_2.query.gz LR/per_sample_SVs/RGP_686_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_686_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_686_3.query.gz LR/per_sample_SVs/RGP_686_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_696_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_696_1.query.gz LR/per_sample_SVs/RGP_696_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_696_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_696_2.query.gz LR/per_sample_SVs/RGP_696_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_696_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_696_3.query.gz LR/per_sample_SVs/RGP_696_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_731_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_731_1.query.gz LR/per_sample_SVs/RGP_731_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_731_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_731_2.query.gz LR/per_sample_SVs/RGP_731_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_731_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_731_3.query.gz LR/per_sample_SVs/RGP_731_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_858_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_858_1.query.gz LR/per_sample_SVs/RGP_858_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_858_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_858_2.query.gz LR/per_sample_SVs/RGP_858_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_858_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_858_3.query.gz LR/per_sample_SVs/RGP_858_3.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_876_1.bed -p SR_vs_LR SR/per_sample_SVs/RGP_876_1.query.gz LR/per_sample_SVs/RGP_876_1.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_876_2.bed -p SR_vs_LR SR/per_sample_SVs/RGP_876_2.query.gz LR/per_sample_SVs/RGP_876_2.ref.gz
bash scripts/compare_callsets_V2.sh -O per_sample_comparison_results/SR_vs_LR.ONT.RGP_876_3.bed -p SR_vs_LR SR/per_sample_SVs/RGP_876_3.query.gz LR/per_sample_SVs/RGP_876_3.ref.gz
